window.onload=function (){

let randInd=Math.floor(Math.random()*10);

let tak=prompt(`Guess which number is generated by computer from 1 to 10`)
tak=Number(tak)


let ej=document.createElement("h3");
ej.style.fontFamily="cursive";
document.body.style.background=("linear-gradient(135deg, #1e1e2f, #3e3e5e)");
document.body.prepend(ej);

if(tak< 1 || tak > 10 || isNaN(tak)){
ej.innerHTML=(`Your number is not between 1 to 10`);
ej.style.color="whitesmoke"
}else{
    if(tak === randInd){
    ej.innerHTML=(`Congratulations! You guess a right number your number ${tak} = computer's number ${randInd}`)
   ej.style.color = "#4dff88";
}
else{
    ej.innerHTML=(`Your number ${tak} not= computer's generated number`);
    ej.style.color = "#ff4d4d";
}
}


}
