let randInd=Math.floor(Math.random()*10);
let b=prompt("Guess which number is generated by computer from 1 to 10")
console.log(randInd)

if(b <= 10 && b > 0 ){
if(b == randInd){
    alert(`Congratulations! You guess a right number your number ${b} = computer's number ${randInd}`);
}else{
    alert(`Your number ${b} not= computer's generated number`)
}
}else{
    alert(`Your number is not between 0 to 10`)
}
